### ISSUE TITLE
Global Destruction Warning

### ISSUE THREAD

**Issue by tomhukins** [cv-library/WebDriver-Tiny#3]
I've written a long test script that uses WebDriver::Tiny.  Every time it runs I see the following warning:

> (in cleanup) Can't call method "_request" on an undefined value at /usr/home/thukins/checkouts/spl/webdriver/local/lib/perl5/WebDriver/Tiny.pm line 355 during global destruction.

I suspect it won't help for me to share my script as it's long and tests a private Web service, but let me know if I can provide any more helpful information.

**Comment by JRaspass** [comment]
So global destruction is a bit of a crapshoot, you can't rely on DESTROY blocks firing in a predictable order. This is an issue for WD::T since it likes to destroy the webdriver session by sending a DELETE request to the webdriver service via a reference to HTTP::Tiny in self and there's a (good)? chance HTTP::Tiny will be freed before WD::T.

Things are generally only destroyed at global destruction when there's a circular reference, at $work we came across this issue with Test::Spec, we filed a bug ( https://github.com/kingpong/perl-Test-Spec/issues/24 ) and it was fixed in 0.50.

Reading back that bug it looks like weakening a reference is another way to avoid keeping WD::T around until global destruction.

I mean one option is to make this failure silent, but I'd rather know that a given test was unable to remove it's session from the webdriver server.
